"""Tests for the autogenerated types."""


class TestRobotIntegration:
    """Test robot package integration and core functionality."""

    def test_types_import(self):
        """Test that robot package imports work correctly."""
        import ark.types  # noqa: F401

    def test_generated_types_have_encode_decode(self):
        from ark.types import generated

        for i in dir(generated):
            # Enumerate all generated types
            if i.endswith("_t"):
                # Ensure they all have "encode" and "decode" methods
                has_encode_decode = hasattr(
                    getattr(generated, i), "encode"
                ) and hasattr(getattr(generated, i), "decode")
                assert has_encode_decode
