[project]
name = "eigen-sensors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "PheelaV", email = "koudas1009@gmail.com" }]
requires-python = "==3.11.*"
dependencies = ["eigen-framework"]

[tool.uv.sources]
eigen-framework = { workspace = true }

[project.scripts]
eigen-sensors = "eigen.sensors:main"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "eigen.sensors"
namespace = true
