simulator:
  name: "my_first_simulator"              # A unique name for your simulator node
  backend_type: "pybullet"                # The physics engine we're using
  node_frequency: 240                     # How often your node's step() function runs (Hz)
  config:
    connection_mode: "DIRECT"                # GUI for visual interface, DIRECT for headless mode
    gravity:                              # Gravity vector [x, y, z] in m/s²
      - 0
      - 0
      - -9.81                             # Standard Earth gravity
    sim_frequency: 240                    # Physics simulation steps per second
  save_render: 
    save_path: "render"                   # Directory where rendered frames will be saved
    remove_existing: false                # Whether to clean the directory before starting
    render_interval: 0.1                  # Save a frame every 0.1 seconds (10 FPS)
    overwrite_file: true                  # Overwrite existing files instead of creating new ones

objects:
  - name: "floor"
    config:
      source: "primitive"
      publish_ground_truth: False

      visual:
        shape_type: "GEOM_BOX"
        visual_shape:
          halfExtents: [1, 1, 0.1]
          rgbaColor: [1.0, 0.0, 0.5, 1.0]  # Pink

      collision:
        shape_type: "GEOM_BOX"
        collision_shape:
          halfExtents: [1, 1, 0.1]

      multi_body:
        baseMass: 0  # Static object

      base_position: [0.0, 0.0, 0.0]
      base_orientation: [0.0, 0.0, 0.0, 1.0]

robots: 
  - name: "SO100"
    config:
      source: "urdf"
      urdf_path: "SO100/so100.urdf"
      class_dir: "/Users/sarthakdas/Documents/Documents - Sarthak’s MacBook Pro 2020/Projects/Eigen Robotics/Codebase/Eigen-Robotics/packages/eigen_robots/src/eigen/robots/SO-100"
      frequency: 240  # Control frequency in Hz
      base_position:
        - 0
        - 0
        - 0.2
      base_orientation:  # Quaternion (x, y, z, w)
        - 0
        - 0
        - 0
        - 1
      use_fixed_base: true
      initial_configuration:  # Starting joint angles
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0