[project]
name = "ark-robots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "PheelaV", email = "koudas1009@gmail.com" }]
requires-python = "==3.11.*"
dependencies = [
    "ark-framework",
    "scipy>=1.15.3",
]

[tool.uv.sources]
ark-framework = { workspace = true }

[project.scripts]
ark-robots = "ark.robots:main"

[project.optional-dependencies]
franka = [
    "franky>=0.0.1",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "ark.robots"
namespace = true

# [tool.uv.build]
# package-dir = "src"
# packages = ["ark"]
